###
### Get API Information
GET http://127.0.0.1:5050/
Accept: application/json

### Get available COM Devices
GET http://127.0.0.1:5050/devices
Accept: application/json

### Select a COM Device
POST http://localhost:5050/devices
Content-Type: application/json

{
  "comDevice": "/dev/cu.usbserial-0001",
  "baudRate": 19200
}

### Get Telescope Information
GET http://localhost:5050/telescope/info
Accept: application/json

### Get Telescope Status
GET http://localhost:5050/telescope/status
Accept: application/json

### Get Telescope Position
GET http://localhost:5050/telescope/position
Accept: application/json

### Set Telescope Date & Time
POST http://localhost:5050/telescope/datetime
Content-Type: application/json

{
  "utcTimestamp": "1653647354",
  "utcOffset": "-120"
}

### Get Telescope Date & Time
GET http://localhost:5050/telescope/datetime
Accept: application/json

### Get Telescope Geolocation
GET http://localhost:5050/telescope/geolocation
Accept: application/json

### Set Telescope Geolocation
POST http://localhost:5050/telescope/geolocation
Content-Type: application/json

{
  "lat": "+49*16",
  "lng": "169*07"
}

### Test Telescope Movement
### Move East
POST http://localhost:5050/telescope/move
Content-Type: application/json

{
  "direction": "e"
}

### Quit East
POST http://localhost:5050/telescope/move/quit
Content-Type: application/json

{
  "direction": "e"
}

### Move South
POST http://localhost:5050/telescope/move
Content-Type: application/json

{
  "direction": "s"
}

### Quit South
POST http://localhost:5050/telescope/move/quit
Content-Type: application/json

{
  "direction": "s"
}

### Move West
POST http://localhost:5050/telescope/move
Content-Type: application/json

{
  "direction": "w"
}

### Quit West
POST http://localhost:5050/telescope/move/quit
Content-Type: application/json

{
  "direction": "w"
}

### Move Noth
POST http://localhost:5050/telescope/move
Content-Type: application/json

{
  "direction": "n"
}

### Quit North
POST http://localhost:5050/telescope/move/quit
Content-Type: application/json

{
  "direction": "n"
}

### Do all Actions
### toggleParking
POST http://localhost:5050/telescope/action
Content-Type: application/json

{
  "action": "toggleParking"
}

### toggleTracking
POST http://localhost:5050/telescope/action
Content-Type: application/json

{
  "action": "toggleTracking"
}

### setHome
POST http://localhost:5050/telescope/action
Content-Type: application/json

{
  "action": "setHome"
}

### Toggle Precision
POST http://localhost:5050/telescope/action
Content-Type: application/json

{
  "action": "togglePrecision"
}

### Reset
POST http://localhost:5050/telescope/action
Content-Type: application/json

{
  "action": "reset"
}

### Slew To (home, target)
POST http://localhost:5050/telescope/slew
Content-Type: application/json

{
  "to": "home"
}

### Set Slew Speed (1-4)
POST http://localhost:5050/telescope/slew/speed
Content-Type: application/json

{
  "speed": 1
}

### Get Target Position
GET http://localhost:5050/target/position
Accept: application/json

### Set Target Position
POST http://localhost:5050/target/position
Content-Type: application/json

{
  "declination": "+90*00'00",
  "rightAscension": "22:10:00"
}